
strain_id_field: "accession"

filter:
  background_group_by: "year country"
  background_set: 500
  focal_set: 1500

country_builds_to_run: [] #["reunion"]

region_builds_to_run: [ "africa", "asia", "south-america"]

# deploy
deploy_url: "s3://nextstrain-staging"
